### PR TITLE
fix stringToFixedPrecision issue.

### LINKED ISSUE #1089: allow manual entry of price
on the margin trading page user cannot type in the amount

### PR DESCRIPTION
**Pull request by rick23p**
closes #1089

### CODE REVIEW

File: src/utils/display-text/format.ts [hunk 1]
```diff
@@ -109,5 +109,13 @@ export function calculateProfit(
   return isLong ? profitLong : profitShort;
 }
 
-export const stringToFixedPrecision = (value: string, precision: number) =>
-  parseFloat(value).toFixed(precision);
+export const countDecimals = value => {
```
Comment (tiltom) [inline src/utils/display-text/format.ts:112]: You don't need to export this function since the only usage is in the same file (and I don't think we would need it elsewhere). 

Also, rename it to `decimalPartLength` please.

File: src/utils/display-text/format.ts [hunk 2]
```diff
@@ -109,5 +109,13 @@ export function calculateProfit(
...
+  if (Math.floor(value) === value || !value.split('.')[1]) return 0;
```
Comment (tiltom) [inline src/utils/display-text/format.ts:113]: I would extract `value.split('.')[1]` to a variable (e.g. `decimalPart`) and use it here as `!decimalPart`.

File: src/utils/display-text/format.ts [hunk 3]
```diff
@@ -109,5 +109,13 @@ export function calculateProfit(
...
+  return value.split('.')[1].length || 0;
```
Comment (tiltom) [inline src/utils/display-text/format.ts:114]: The OR part is unnecessary here since you do all the checks before + you can use newly created variable as `decimalPart.length`.

File: src/utils/display-text/format.ts [hunk 4]
```diff
@@ -109,5 +109,13 @@ export function calculateProfit(
...
+};
+
+export const stringToFixedPrecision = (value: string, precision: number) => {
+  if (countDecimals(value) > precision)
+    return parseFloat(value).toFixed(precision);
+  else return value;
```
Comment (tiltom) [inline src/utils/display-text/format.ts:120]: Unnecessary `else`, you can just return.

**Review by tiltom — CHANGES_REQUESTED** [review]

File: src/utils/display-text/format.ts (hunk 1 above)
Comment (tiltom) [reply src/utils/display-text/format.ts:112]: Why you didn't address this comment? Let me know if you have another opinion on it but I think those are valid arguments.

File: src/utils/display-text/format.ts [hunk 5]
```diff
@@ -109,5 +109,15 @@ export function calculateProfit(
   return isLong ? profitLong : profitShort;
 }
 
-export const stringToFixedPrecision = (value: string, precision: number) =>
-  parseFloat(value).toFixed(precision);
+export const countDecimals = value => {
+  if (!value) return;
```
Comment (tiltom) [inline src/utils/display-text/format.ts:113]: You don't need this, just use `value?.split('.')[1];` on the next line.

File: src/utils/display-text/format.ts [hunk 6]
```diff
@@ -109,5 +109,15 @@ export function calculateProfit(
...
+  const decimalPart = value.split('.')[1];
+  return decimalPart ? decimalPart.length || 0 : 0;
```
Comment (tiltom) [inline src/utils/display-text/format.ts:115]: You could rewrite it to `return decimalPart?.length ?? 0`.

**Review by tiltom — CHANGES_REQUESTED** [review]

**Review by tiltom — APPROVED** [review]

**Review by t-z-u — APPROVED** [review]
